### ISSUE TITLE
cvmfs content for cvmfs-atlas

### ISSUE THREAD

**Issue by berghaus** [hepsw/docks#5] opened 2015-04-27 14:56 UTC
Hi,

I'm trying to setup the ATLAS software environment. On by way there I ran into this issue when looking into the atlas.cern.ch repository:

```
$ docker run --privileged hepsw/cvmfs-atlas -c "ls /cvmfs/"
atlas-condb.cern.ch 
atlas.cern.ch
cernvm-prod.cern.ch
sft.cern.ch

$ docker run --privileged hepsw/cvmfs-atlas -c "ls /cvmfs/atlas.cern.ch/"

$ docker run --privileged hepsw/cvmfs-atlas -c "ls /cvmfs/atlas.cern.ch/repo"
ls: cannot access /cvmfs/atlas.cern.ch/repo: No such file or directory
```

That last directory *should* be getting cached in. So the repository exists, but I cannot get any of the content in the repository.

**Comment by sbinet** [comment] 2015-04-27 17:10
Hi Frank,
I am currently on the move. I'll have a look at this next week.

**Comment by berghaus** [comment] 2015-04-28 14:12
Thanks! Happy travels.

**Comment by sbinet** [comment] 2015-05-07 11:32
hi Frank,

when you run the container like so:

```sh
$ docker run --privileged hepsw/cvmfs-atlas -c "some command"
```

the `/root/.bashrc` file is not executed so `/root/run-cvmfs.sh` is, in turn, not run.
so, no `CVMFs` daemon is running, hence, no real meat under `/cvmfs/xyz`.

the following works, though:

```sh
$ docker run --privileged hepsw/cvmfs-atlas -c "/root/run-cvmfs.sh; ls /cvmfs/atlas.cern.ch/repo/"
::: mounting FUSE...
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/cernvm-prod.cern.ch
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/sft.cern.ch
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/atlas.cern.ch
CernVM-FS: running with credentials 499:497
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/atlas-condb.cern.ch
::: mounting FUSE... [done]
ATLASLocalRootBase
conditions
dev
sw
tools
```

I am tempted to close this as "working as intended" although I am quite aware launching the `CVMFs` daemon in a more robust way is in dire need.

(so... closing, but feel free to re-open)

**Closed by sbinet** 2015-05-07 11:32 UTC
